// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./../src/components/Avatar/index.vue')['default']
    CategoryList: typeof import('./../src/components/CategoryList/index.vue')['default']
    Comment: typeof import('./../src/components/Comment/index.vue')['default']
    CommentInput: typeof import('./../src/components/CommentInput/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./../src/components/Footer/index.vue')['default']
    Header: typeof import('./../src/components/Header/index.vue')['default']
    HotPostList: typeof import('./../src/components/HotPostList/index.vue')['default']
    Post: typeof import('./../src/components/Post/index.vue')['default']
    PostRecommend: typeof import('./../src/components/PostRecommend/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../src/components/SearchInput/search.vue')['default']
    SplitLine: typeof import('./../src/components/SplitLine/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    UserProfile: typeof import('./../src/components/UserProfile/index.vue')['default']
    UserProfileDefaultModel: typeof import('./../src/components/UserProfileModel/UserProfileDefaultModel/index.vue')['default']
  }
}
