// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./../src/components/avatar/index.vue')['default']
    CategoryList: typeof import('./../src/components/category-list/index.vue')['default']
    Comment: typeof import('./../src/components/comment/index.vue')['default']
    CommentInput: typeof import('./../src/components/comment-input/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./../src/components/footer/index.vue')['default']
    Header: typeof import('./../src/components/header/index.vue')['default']
    HotPostList: typeof import('./../src/components/hot-post-list/index.vue')['default']
    Index: typeof import('./../src/components/LeftPanel/Index.vue')['default']
    LeftPanel: typeof import('./../src/components/LeftPanel/index.vue')['default']
    Post: typeof import('./../src/components/post/index.vue')['default']
    PostRecommend: typeof import('./../src/components/PostRecommend/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('../src/components/header/components/search-input/search.vue')['default']
    SearchInput: typeof import('./../src/components/header/components/search-input/index.vue')['default']
    Skeleton: typeof import('./../src/components/skeleton/index.vue')['default']
    SplitLine: typeof import('./../src/components/split-line/index.vue')['default']
    SvgIcon: typeof import('./../src/components/svg-icon/index.vue')['default']
    UserProfile: typeof import('./../src/components/UserProfile/index.vue')['default']
    UserProfileDefaultModel: typeof import('./../src/components/user-profile-model/user-profile-default-model/index.vue')['default']
  }
}
